--- 
title: "Data Science in Action During an Pandemic, Spring 2020"
author: "Jun Yan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
# bibliography: [stco.bib, book.bib, packages.bib]
biblio-style: chicago
link-citations: yes
description: "This is a series of notes for the students of 
  a seminar course taught at School of Statistics, SXUFE."
---

# 03/06

1. Going over the syllabus
1. Project management
   + Grouping
   + Member contributions
1. Presentation management
   + Sign up sheet?
1. Project ideas
   + Number of deaths due to COVID-19
   + Times series of historical data
   + Application and extension of eSIR
1. On Git and GitHub
   + It's a great tool
   + Not hard to pick up as long as you keep using it
   + Not that easy either

# 03/13

1. Questions from Git exercises
1. Demo Git clone, reproducible work, and contributions
   + Zhang, Yan (Chinese file name; location of working directory)
   + Xiao, Shiying
   + Jiao, Jieying
1. Building the Bookdown book from source
1. Discussion of Song's work (possible projects)
1. Logistics
   + Form teams
   + Sharpen skills
   + Identifying research questions
   + Find data
   + Proposal is due by week 5
1. Webinar and conference

# 03/20

1. Git issues; pull request
1. Demo from Shiying Xiao
1. Points of the building from source
    + It's the learning process that is of importance
	+ Search the error message
1. Logistics
    + Form teams
	    - Team leader
		- Team name
	+ Sign up
	+ Topic presentation resources
	    - arXiv; bioRXiv, medRXiv
		- Statistics Forum
	+ Time (lecture, study, and research)
1. A case study: ABO blood type and COVID-19


# 03/27

1. Examples of topic presentations
    + Styles/Formats
	+ Code for reproducibility
	+ Topics (Tom Kennen; Yishu Xue; Yiming Zhang)
1. Data sources
1. Logistics
    + Teams and proposals
	+ Coaches


# 04/03

1. Reproducibility (use relative path; etc.)
1. Tidyness (spacing; indentation; generated files; folders)
1. Git style: commit often; informative message
1. RMarkdown style:
    + keep the code clean and human-eye friendly
    + Use presentation style for presentations
1. Writing: 
    + Credit where it is due
	+ Back you what you say with citations
	+ Clarify your contribution in position of the existing literature


# 04/10

1. Logistics
    + Interim report is due on Friday, May 22
	+ Confirm that your team has a coach
	+ Use "Issues" on GitHub to communicate
	+ Search/review the literature, always
	+ The final presentation order is to be determined at random
1. Guidelines for future presentations
    + The presentations are reproducible from the repo sources
	+ Full screen
	+ Use the presentation output format for RMD sources
	+ Check your audio volume
	+ Keep it strictly within 30 minutes
	+ Watch your style (e.g., gamma in text mode and math mode are
      different notations)
	+ Learn from each other --- the repos are all public

# 04/24

A project presentation is different from topic presentation

+ Project presentation focuses on your research question
    - Why is it important?
	- What's been done?
	- What's your contribution?
	- What're the take-home messages?
	- It is a research presentation as in a research conference
	    + Focus on results
		+ Skip implementations unless the implementation is your
          research quesitons like in statistical computing
+ A project progress report can report unsolved problems, potential
  solutions, fall-back plans, discussion on limitations of the current
  methods.

# 05/08

Suggestions for presentation:

+ Introduce yourself
+ Be aware of time (several levels at the JSM)
+ Do not read
+ Slides are not to be the same as the article (font; figure; table; etc.)
+ Learn form others

Suggestions on project research:

+ Review the literature
+ Be critical
+ Presentation in slides; report in article
+ Citation style (give credit where it's due)

Comments

+ Team Happy
    - Qi, Ding, and Wu presented
    - Convergence check?
    - Zhiwei Li; Mengtao Cui; Yuzhi Liu

+ Guardian of the Galaxy
    - Moran's I; zscore; Monte Carlo
    - High-low vs low-high
	- Decomposition: direct/indirect
	- Xiaohan Liu; Ruiling Yu
	
+ Alien adventure
    - Count data
	- Fan Qi

+ Victor
    - Heterogeneity among the provinces
	- Parameter setting: needs time-varying?
	- Peak in the plot meaning?
	- What're the parameters to be estimated?
	- Yao Wang; Yalin He; Xiaohan Liu; Yan Zhang; Xiaofang Feng;
      Xiaorui Zhang; Lijiao Liu; Fang Guo
	
# 05/15

Openning

+ Tips of presentations
+ Keep GitHub repo updated
+ Don't forget final presentation order


Rainbow

+ Parameter determination?
+ Tuning parameter in sann?
+ Mengtao Cui; Hongyu Cheng

Pull Wind

+ Covariates at input?
+ Prediction uncertainty?
+ Xiaofang Feng; Yanmei Gao; Yalin He; Xuejiao Cao; Ruiling Yu

Sunshine

+ Stationarity in variance?
+ 4.8701%?
+ 2.5 vs 1.9
+ Uncertainty
+ Prediction vs observed in March (export) (h-step ahead?)
+ Min Zhao; Xiaodan Wei

The One

# 05/22

## Rockets

+ CCF: how to define lag? Stationarity?
+ CCF results? what lag?
+ Qingqing Liang; Xueli Wang; Fan Wang

## Happy Beatles

+ Wang Xueqin's work
+ Data source (imported vs non-imported)
+ Raidar plot
+ Jump in synthetic line?
+ Yalin He

## Wonder Woman

+ R package for nonlinear regression?
+ Standardization process?
+ Clustering: preprocessing variables?
+ Weekly pattern for Russian/Brazil?
+ Goodness-of-fit?

## Lucky Girls

+ Red dots meaning
+ n.ahead?
+ prediction + variation
+ Validation of forecasting
+ KNN's time domain for rare event
+ Yin Liu; Xiaorui Zhang


## Guidelines for the Final Presentation and Final Report

+ Presentation is presentation; report is report
+ Authors' contribution statement in the report
+ A report is a paper (title, abstract, introduction,
  methods/models/analysis, discussion/conclusion, references)
+ Code/data should be in the repo for reproducibility

# 05/29 (final presentation 1)

## Wonder Woman

+ Order of countries on page 3?
+ Jie Yang;

## Tsia

+ English name for the model?
+ Quarantine measure specifics?
+ Hongyu Cheng; Ruizhe Mo; 

## Pull Wind

+ adam? optimizer?
+ Huijun Mu; Jinping Lu

## Guardians of the Galaxy

+ Baidu crawler
+ Scan applied to points or areal data?
+ Guangzi Liu; Ruizhe Mo


# 06/05 (final presentation 2)

+ Reproducibility: figures/tables
    - A whole cycle from raw data to results
+ Figures: pdf or ps (never png or jpg)

## Team Happy

+ Presented by Yan Zhang, Yaran Qu
+ Questions addressed by Bixuan Wu

## Happy Beatles

+ Presented by Minghui Li, Ruixin Han (interim report was done by the
  other two members of the team)
+ What does it mean by delayed by one day or 7 days?
+ Average growth rate in each period assumption?

## Rainbow

+ Plots: page 20; page 22;
+ A nice plot (left: rate Wuhan immigrant; rate of confirmed cases)

## Rockets

+ page 7
+ AIC? Group 1 vs group 2?
+ Reference (BNU, Nature)?
+ Jingping Lu; Qingqing Liang

# 06/12 (final presentation 3)

+ Form a good working style; "Add files via upload"?
+ Check out latex symbol list: $\log$, $\exp$, $\sigma$, etc.
+ Final report: 11:59pm, 6/26/2020

## The One 
+ RR
+ Offset
+ Model diagnostics
+ Hongyu Cheng; Chao Tian

## Lucky Girls
+ Why input missing holiday values?
+ VaR details?
+ 20-day ahead forecast?
+ Rolling prediction setting?

## Alien Adventure

+ Selection of smoothing parameter?

## Victor

+ Control coefficient $k$?
+ Exponential decaying of Rt: justification?
+ SEIR data versus parameters?
+ Uncertainty measure in parameter estimation?

## Summary

+ Final report due: 11:59pm, 6/26/2020
+ Reproducibility
